### ISSUE TITLE
Add a layer that shows shifts in census tracts  

### ISSUE THREAD

**Issue by nsunami** [de-data-lab/map-tract-lineage#4]
Add a layer that shows shifts in census tract boundaries from 2010 to 2020. 

One purpose is to highlight the areas affected by redistricting.

**Comment by ddil-projects** [comment]
Choosing a map background that really shows the units/areas that are being shifted might help in the interpretation too. I am not sure which map background/layout is the best, but I'd say explore for feasibility!
